// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"time"
)

type Meal struct {
	UserID    int64
	Day       time.Time
	Breakfast string
	Snack1    string
	Lunch     string
	Snack2    string
	Dinner    string
}
